# Generated by Django 4.2.7 on 2024-01-17 02:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0002_rename_mno_tuv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tuv',
            new_name='uh',
        ),
    ]
